services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: spaces-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP protocol for Next.js & Worker
      - "15672:15672"  # RabbitMQ Management Web Dashboard (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
